footprint: [[0.35,0.28],[-0.35,0.28],[-0.35,-0.28],[0.35,-0.28]]
footprint_padding: 0.1

#map_type: costmap
#min_obstacle_height: 0.05
max_obstacle_height: 0.25
#obstacle_range: 10
#raytrace_range: 16

obstacles_layer:
  enabled: true
  track_unknown_space: true #像素具有三种状态，致命障碍/自由/未知
  combination_method: 1
#  max_obstacle_height: 0.25    #障碍物最大高度，应略高于机器人高度
#  min_obstacle_height: 0.05    #障碍物最低高度
  footprint_clearing_enabled: true #清除机器人足迹
  
  obstacle_range: 10
  raytrace_range: 15
  observation_sources: scan 
  scan: 
    sensor_frame: laser_frame
    data_type: LaserScan
    clearing: true
    marking: true
    topic: /scan  
    observation_persistence: 0.0 #传感器数据保持时间，0.0保持最新数据 
#    expected_update_rate: 0.2 #从传感器读数的间隔时间的保障时间，数值应略大于实际传感器读数的间隔时间，0.0为无限时间
    max_obstacle_height: 0.22 #过滤掉传感器中高于该高度的点
    min_obstacle_height: 0.02
    obstacle_range: 10
    raytrace_range: 15
    inf_is_valid: false #是否允许传感器读书中inf值，inf值转换成laser最大值
   

local_inflation_layer:
  enabled: true
  inflation_radius: 0.20 #机器人膨胀半径
  inflate_unknown: true #膨胀到未知区域 
  cost_scaling_factor: 5.0 #代价比例系数，越大代价值越小；代价值最大253；
#代价值 = exp(-1.0 * cost_scaling_factor * (distance_from_obstacle - inscribed_radius)) * (costmap_2d::INSCRIBED_INFLATED_OBSTACLE - 1)
#costmap_2d::INSCRIBED_INFLATED_OBSTACLE=254

global_inflation_layer:
  enabled: true
  inflation_radius: 0.5 #机器人膨胀半径
  cost_scaling_factor: 2.0 #代价比例系数，越大代价值越小；代价值最大253；
  inflate_unknown: true #膨胀到未知区域

static_layer:
  enabled: true
#  map_topic: /map
#  subscribe_to_updates: true
#  track_unknown_space: true 




