NavfnROS:
  allow_unknown: false # 是否允许穿过未知区域
  default_tolerance: 0.0 # 路径规划点与目标点的偏差距离
  visualize_potential: true #是否允许发布点云表达的代价趋势
  planner_window_x: 0.0
  planner_window_y: 0.0


GlobalPlanner:
  old_navfn_behavior: true #是否使用旧版导航功能呢个，默认false
  allow_unknown: false #不允许未知区域路径规划
#  track_unknown_space: true


  use_dijkstra: false # false:A* Path; true: D* Path

  use_quadratic: true #是否采用二阶逼近的趋势；默认为true，否则采用简单的线性方法
  use_grid_path: false # 是否沿着网格规划路径，默认为False,false时采用最速下降法计算路径

  planner_window_x: 0.0
  planner_window_y: 0.0

#  default_tolerance: 0.5 #若目标点在障碍物上，规划点与目标点的偏差
  
  
  lethal_cost: 253 #最高的代价值，默认253
  neutral_cost: 50 #中性代价系数
  cost_factor: 3.0 #占用网格的系数
  publish_potential: true #是否发布趋势

  orientation_mode: 3 #方向设置，默认0采用默认坐标系
  orientation_window_size: 2 #方向窗口大小

#  publish_scale: 100
#  planner_costmap_publish_frequency: 0.0
  
